import { SocialProof } from "@/components/social-proof"
import { DemoGallery } from "@/components/demo-gallery"
import Image from "next/image"
import { DownloadDropdown } from "@/components/download-dropdown"
import { getLatestRelease, getDownloadCount } from "@/lib/downloads"
import { SiteNav } from "@/components/site-nav"
import { SiteFooter } from "@/components/site-footer"
import { Reveal } from "@/components/reveal"
import { CopyCommand } from "@/components/copy-command"
import { Comparison } from "@/components/home/comparison"
import { FaqSection, faqs } from "@/components/home/faq"
import { ProductFeatures, ProductLink, ProductPreview } from "@/components/product-showcase"

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.q,
    acceptedAnswer: { "@type": "Answer", text: faq.a },
  })),
}

function formatCount(n: number): string {
  if (n >= 1000) return `${(n / 1000).toFixed(1).replace(/\.0$/, "")}K+`
  return String(n)
}

const performanceHighlights = [
  {
    stat: "Native",
    label: "macOS",
    body: "Built with Swift and AppKit. No Electron, no bundled browser, no web wrapper.",
  },
  {
    stat: "On-device",
    label: "transcription",
    body: "Captions generated by Apple's speech framework. Audio never touches a server.",
  },
  {
    stat: "30 Hz",
    label: "pointer tracking",
    body: "Cursor sampled 30 times per second for smooth, automatic zoom moves.",
  },
  {
    stat: "Crash-safe",
    label: "MP4",
    body: "Fragmented MP4 writes every frame as it arrives. Quit mid-recording, keep the file.",
  },
]

const moreFeatures = [
  { title: "75 customizable shortcuts", body: "Global captures, recording controls, deck actions, image tools, and video editing keys. Search, filter, and rebind with conflict detection." },
  { title: "URL scheme", body: "Trigger captures, recordings, OCR, or color picker from Raycast, Shortcuts, Alfred, or scripts with bettershot:// URLs." },
  { title: "Auto-save recordings", body: "Finished recordings save to your configured folder automatically. Manual Save on deck cards writes recordings too." },
  { title: "Backgrounds and beautify", body: "Padding, shadow, corner radius, and ten soft gradient backgrounds. Presentable screenshots and videos without a second app." },
  { title: "Cursor styling", body: "Recorded, Arrow, Dark, Light, or Dot cursor with adjustable size, motion smoothing, press effects, and idle hiding." },
  { title: "No watermark, no account", body: "Every export is clean. No trial, no upsell. BSD 3 Clause licensed and auditable." },
]

export default async function Home() {
  const [release, downloads] = await Promise.all([getLatestRelease(), getDownloadCount()])

  const stats = [
    { value: "$0", label: "Forever. No tiers, no trial" },
    { value: downloads > 0 ? formatCount(downloads) : "Open source", label: downloads > 0 ? "GitHub release downloads" : "Built in the open" },
    { value: "macOS", label: "Native from capture to export" },
  ]

  return (
    <div className="min-h-screen bg-white text-zinc-900">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <SiteNav />

      <main id="main" className="landing-page">
        <section className="pb-12 pt-24 sm:pt-28">
          <div className="mx-auto max-w-[1100px] px-6 text-center">
            <p className="mb-5 text-sm font-medium text-brand">Screenshots &amp; screen recording for Mac</p>
            <h1 className="hero-title">
              Capture clearly.<br />Share beautifully.
            </h1>
            <p className="mx-auto mt-6 max-w-xl text-lg leading-relaxed text-zinc-600">
              Record a walkthrough, polish a screenshot, and share your best work.
              One native Mac app. Free and open source.
            </p>

            <Reveal>
              <div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">
                <DownloadDropdown release={release} source="hero" />
                <a
                  href="#demo"
                  className="text-[15px] font-medium text-zinc-600 transition-colors hover:text-zinc-900"
                >
                  Watch the launch video &rsaquo;
                </a>
              </div>
            </Reveal>

            <Reveal>
              <div className="mt-8 flex justify-center"><SocialProof downloads={downloads} /></div>
            </Reveal>

          </div>
        </section>

        <div id="demo" className="mx-auto max-w-[1360px] scroll-mt-20 px-6">
          <DemoGallery showLaunchVideo />
          <div className="mt-6 flex flex-wrap justify-center gap-x-8 gap-y-4"><ProductLink kind="video" /><ProductLink kind="image" /></div>
        </div>

        <Reveal as="section" className="mx-auto max-w-[1100px] px-6 py-14" aria-label="Better Shot in numbers">
          <div className="grid grid-cols-1 gap-7 text-center sm:grid-cols-3 sm:divide-x sm:divide-zinc-200">
            {stats.map((stat) => (
              <div key={stat.value} className="px-5 py-2">
                <p className="text-[clamp(28px,3vw,42px)] font-semibold leading-[1.1] tracking-tight text-zinc-900">
                  {stat.value}
                </p>
                <p className="mt-2 text-[13px] leading-[18px] text-zinc-600">{stat.label}</p>
              </div>
            ))}
          </div>
        </Reveal>

        <section id="features" className="mx-auto max-w-[740px] scroll-mt-20 px-6 pb-4 pt-16 text-center sm:pt-24">
          <p className="mb-4 text-sm font-medium text-brand">Video recording</p>
          <h2 className="text-[38px] font-semibold leading-[1.08] sm:text-[56px]">A quick take.<br />A better walkthrough.</h2>
          <p className="mx-auto mb-6 mt-6 max-w-xl text-[17px] leading-relaxed text-zinc-600">Record your screen and camera, guide the eye with cursor effects, and cut straight to the good part.</p>
          <ProductLink kind="video" />
        </section>
        <ProductFeatures kind="video" />

        <section className="py-16 sm:py-24">
          <div className="mx-auto grid max-w-[1360px] items-center gap-12 px-6 md:grid-cols-[0.7fr_1.3fr]">
            <div><p className="mb-4 text-sm font-medium text-brand">Screenshots</p><h2 className="text-[38px] font-semibold leading-[1.08] sm:text-[56px]">Small capture.<br />Clear message.</h2><p className="mb-6 mt-5 text-base leading-relaxed text-zinc-500">An arrow in the right place. A detail kept private. A little room around your image. Small edits that make your message land.</p><ProductLink kind="image" /></div>
            <ProductPreview kind="image" />
          </div>
        </section>
        <ProductFeatures kind="image" />

        <section className="bg-zinc-50 py-16 sm:py-24">
          <div className="mx-auto max-w-[1100px] px-6">
            <Reveal className="mx-auto mb-14 max-w-lg text-center">
              <p className="mb-3 text-[13px] font-medium uppercase tracking-widest text-zinc-400">
                Performance
              </p>
              <h2 className="text-[28px] tracking-tight sm:text-[32px]">
                Built for macOS, not for Electron
              </h2>
              <p className="mt-4 text-[16px] leading-relaxed text-zinc-600">
                Native from top to bottom. Light on CPU, light on battery, fast on every Mac.
              </p>
            </Reveal>

            <Reveal className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
              {performanceHighlights.map((item) => (
                <div key={item.stat} className="rounded-2xl border border-zinc-200 bg-white p-6">
                  <p className="text-[24px] tracking-tight text-brand">{item.stat}</p>
                  <p className="text-[13px] font-semibold uppercase tracking-widest text-zinc-400">{item.label}</p>
                  <p className="mt-3 text-[13px] leading-relaxed text-zinc-600">{item.body}</p>
                </div>
              ))}
            </Reveal>
          </div>
        </section>

        <section className="py-16 sm:py-24">
          <div className="mx-auto max-w-[1100px] px-6">
            <Reveal className="mx-auto mb-12 max-w-lg text-center">
              <h2 className="text-[28px] tracking-tight sm:text-[32px]">
                And everything else you need
              </h2>
              <p className="mt-4 text-[16px] leading-relaxed text-zinc-600">
                From raw capture to the file you send, nothing missing.
              </p>
            </Reveal>

            <Reveal className="grid gap-px overflow-hidden rounded-2xl border border-zinc-200 bg-zinc-200 sm:grid-cols-2 lg:grid-cols-3">
              {moreFeatures.map((f) => (
                <div key={f.title} className="bg-white p-6 transition-colors hover:bg-zinc-50">
                  <h3 className="text-[15px] font-semibold text-zinc-900">{f.title}</h3>
                  <p className="mt-2 text-[13px] leading-relaxed text-zinc-600">{f.body}</p>
                </div>
              ))}
            </Reveal>
          </div>
        </section>

        <section id="getting-started" className="scroll-mt-20 bg-zinc-50 py-16 sm:py-24">
          <div className="mx-auto max-w-[1100px] px-6">
            <h2 className="text-balance text-[28px] sm:text-[32px]">Your first capture, in three steps</h2>
            <p className="mt-4 max-w-xl text-[16px] leading-relaxed text-zinc-600">
              Start with the menu bar. Set up the extras when you need them.
            </p>
            <ol className="mt-10 grid gap-8 md:grid-cols-3">
              {[
                { title: "Open BetterShot", body: "Install the app, then find the clover in your Mac’s menu bar. It’s your way back to captures, recent work, and Settings." },
                { title: "Choose what to capture", body: "Take a screenshot or open Recording options. Choose a display, window, or area. Include your camera or microphone only when you need them." },
                { title: "Make your point", body: "Open Edit from the preview. Add an arrow or a note to an image, or refine a recording. Export a file locally; cloud sharing is optional." },
              ].map((step, index) => (
                <li key={step.title}>
                  <span className="text-[14px] font-medium tabular-nums text-zinc-500">0{index + 1}</span>
                  <h3 className="mt-3 text-[18px] font-semibold">{step.title}</h3>
                  <p className="mt-2 text-[15px] leading-relaxed text-zinc-600">{step.body}</p>
                </li>
              ))}
            </ol>
            <p className="mt-10 max-w-2xl text-[14px] leading-relaxed text-zinc-600">
              New in 0.5.2: capture on mouse release, URL scheme for automation, auto-save
              recordings, and 75 customizable shortcuts. See the{" "}
              <a href="/changelog" className="text-brand-700 underline underline-offset-2 hover:text-brand">changelog</a>{" "}
              for the full list.
            </p>
          </div>
        </section>

        <Comparison />

        <FaqSection />

        <Reveal as="section" className="py-20 sm:py-28">
          <div id="download" className="mx-auto max-w-lg scroll-mt-20 px-6 text-center">
            <Image
              src="/logo.png"
              alt="Better Shot"
              width={64}
              height={64}
              className="mx-auto mb-8 rounded-2xl shadow-lg shadow-brand/10"
            />
            <h2 className="text-[28px] tracking-tight sm:text-[32px]">
              Ready to try Better Shot?
            </h2>
            <p className="mt-4 text-[16px] leading-relaxed text-zinc-600">
              Free, open source, installed in about thirty seconds.
            </p>
            <div className="mt-8 flex flex-col items-center gap-4 sm:flex-row sm:gap-5 sm:justify-center">
              <DownloadDropdown release={release} source="cta" size="default" />
              <CopyCommand command="brew install --cask bettershot" />
            </div>
            <p className="mt-4 text-[13px] text-zinc-400">
              No account. No subscription. No uploads. macOS 26.0+.
            </p>
          </div>
        </Reveal>
      </main>

      <SiteFooter />
    </div>
  )
}
